#!/usr/bin/env python
#-*- coding:UTF-8 -*-
'''
Publish commands to the salt system from the command line on the master.
'''
import os
import sys
reload(sys)
sys.setdefaultencoding('utf8')

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, "../packages")))

from salt.scripts import salt_cp


if __name__ == '__main__':
    salt_cp()
