#!/usr/bin/env python
#-*- coding:UTF-8 -*-
'''
Directly call a salt command in the modules, does not require a running salt
minion to run.
'''
import os
import sys
reload(sys)
sys.setdefaultencoding('utf8')

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, "../packages")))

from salt.scripts import salt_call


if __name__ == '__main__':
    salt_call()
