#!/usr/bin/env python
#-*- coding:UTF-8 -*-
'''
This script is used to kick off a salt syndic daemon
'''
import os
import sys
reload(sys)
sys.setdefaultencoding('utf8')

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, "../packages")))

from salt.scripts import salt_syndic


if __name__ == '__main__':
    salt_syndic()
