#!/usr/bin/env python
#-*- coding:UTF-8 -*-
'''
This script is used to kick off a salt minion daemon
'''
import os
import sys
reload(sys)
sys.setdefaultencoding('utf8')

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, "../packages")))

from salt.scripts import salt_minion
from multiprocessing import freeze_support


if __name__ == '__main__':
    # This handles the bootstrapping code that is included with frozen
    # scripts. It is a no-op on unfrozen code.
    freeze_support()
    salt_minion()
